hashicorp/flight

ember-flight-icons/package.json

Reverts hashicorp/flight#46
This change actually breaks the addon because references to the package need to also be updated. Let's revert to get things working and revisit this and ensure tests are passing before merging.

Revert "update package name to @hashicorp/ember-flight-icons"

---

ember-flight-icons/addon/components/flight-icon.hbs
ember-flight-icons/app/components/flight-icon.js
ember-flight-icons/package.json

Attempt 2 at https://github.com/hashicorp/flight/pull/46 except more (all 🤞 ) places are now updated to reflect the change
✅  tests pass locally

rename package to @hashicorp/ember-flight-icons

---

.gitignore

If merged, this PR adds the `node_modules` folder to the `.gitignore` file at the root of the repository.

added node_modules to gitignore

---

ember-flight-icons/config/ember-try.js

Addresses https://github.com/hashicorp/flight/pull/95 by allowing the flaky tests to fail without failing the overall build

allow canary and embroiderOptimized scenarios to fail

---

ember-flight-icons/README.md
ember-flight-icons/addon/components/flight-icon.js
ember-flight-icons/tests/dummy/app/templates/application.hbs
ember-flight-icons/tests/integration/components/flight-icon-test.js

If merged, this PR resolves #78 
Please consider using [conventional comments](https://conventionalcomments.org/) when reviewing this PR.
This PR changes the default size of the icon from 24x24 to 16x16. The tests and documentation were also updated to reflect the changes made in the component.
Note: Two test scenarios, `ember-canary` and `embroider-optimized` are not currently passing. We have confirmed that the `ember-canary` scenario is widespread and not due to this addon. We are looking into the `embroider-optimized` scenario but as we are not currently using embroider or optimizing for it, it is not a blocker if this scenario does not pass right now.

Changes default icon size to 16x16

---

ember-flight-icons/addon/components/flight-icon.hbs
ember-flight-icons/tests/integration/components/flight-icon-test.js

If merged, this PR resolves the issue where currentColor was not being inherited correctly.
- updated component template to pass `currentColor` correctly
- added tests to check that the default works as expected, and that currentColor is inherited correctly.

bug: resolved issue where currentColor was not being set properly

---

.github/CODEOWNERS.md

I missed the `*` before.
Fix to: https://github.com/hashicorp/flight/pull/104
Ref: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-code-owners

Fix CODEOWNERS functionality

---

ember-flight-icons/tests/dummy/app/components/dummy-nav.hbs
ember-flight-icons/tests/dummy/app/controllers/index.js
ember-flight-icons/tests/dummy/app/router.js
ember-flight-icons/tests/dummy/app/routes/application.js
ember-flight-icons/tests/dummy/app/routes/design.js
ember-flight-icons/tests/dummy/app/routes/engineering.js
ember-flight-icons/tests/dummy/app/routes/index.js
ember-flight-icons/tests/dummy/app/styles/app.css
ember-flight-icons/tests/dummy/app/templates/application.hbs
ember-flight-icons/tests/dummy/app/templates/design.hbs
ember-flight-icons/tests/dummy/app/templates/engineering.hbs
ember-flight-icons/tests/dummy/app/templates/index.hbs

If merged, this PR resolves issue #121 
Examples: 
- added `design` and `engineering` routes to dummy app
- added navbar component to dummy app
- added styles to support navbar to dummy app
- added an `index` template to dummy app
- moved some of the application template code to the index template 
- moved controller code from application controller to index controller
- moved the router code from the application router to the index router
Needs more styling for the navbar, not sure …

feature: added routes for design and engineering documentation

---

ember-flight-icons/tests/integration/components/flight-icon-test.js

If merged, this PR removes the comments from the test file. 
Examples: 

fix: removes comments from test file

---

ember-flight-icons/tests/dummy/app/index.html

Currently there is a brief moment during load where the title of the page is `Dummy`. This PR changes that to `Flight Icons`.

add default title to docs app

---

ember-flight-icons/tests/dummy/app/styles/app.css
ember-flight-icons/tests/dummy/app/templates/engineering.hbs

If merged, this PR adds consumer instructions for engineers. Note: this is a diversion from the original plan, after discovering that it wasn't quite possible yet ([see related issue](https://github.com/gcollazo/ember-cli-showdown/issues/54))
:speech_balloon:  Please consider using [conventional comments](https://conventionalcomments.org/) when reviewing this PR.
Examples: 
adding instructions for designers may be done in a separate PR.
Visit the deploy preview directly: …

enhancement: consumer instructions for engineers

---

ember-flight-icons/addon/components/flight-icon.hbs
ember-flight-icons/addon/styles/app.css
ember-flight-icons/tests/integration/components/flight-icon-test.js

If merged, this PR resolves #150 by adding additional namespacing to the component css classes. I also re-arranged the properties in the component itself so height/width/viewbox were grouped together, for easier maintenance (based on feedback from @didoo). 
After this PR and PR #149 are merged, I'll update the documentation and the README files to align.
Examples: 

bugfix: resolve issue where not all the css classes were namespaced

---

ember-flight-icons/tests/dummy/app/styles/app.css
ember-flight-icons/tests/dummy/app/templates/engineering.hbs

If merged, this PR adds additional information to the docs for engineers. Includes links at the top of the page types of use.
See: https://flight-git-feature-update-eng-docs-hashicorp.vercel.app/engineering specifically.
Examples: 

enhancement: improved engineer docs

---

.github/workflows/ci-ember-flight-icons.yml
ember-flight-icons/package.json

ember-cli has dropped support for this, it's been EOL for some time and I believe we can drop support for it as well as I'm not aware of any consumer apps on a node version this old (and if they are they should probably upgrade!)

drop support for node 10

---

.github/pull_request_template.md

While filling out a PR with this template it's distracting having a large section of text that is for the reviewer mixed in with content that the PR author needs to fill out. To try to help with this I propose we move that section to the. bottom as the last thing a reviewer would read before looking at the PR.
Examples: 

move conventional comments prompt to bottom

---

ember-flight-icons/config/ember-try.js

Known issue with ember-cli-postcss https://github.com/embroider-build/embroider/issues/688
I think it would be worth consdiering either not running this step at all since allowing it to fail is effectively the same thing or extracting out the docs so issues with them don't affect our ability ensure embroider compat for consumers of the addon itself.

allow embroiderSafe to fail

---

ember-flight-icons/tests/dummy/app/styles/nav.css
ember-flight-icons/tests/dummy/app/styles/typography.css
ember-flight-icons/tests/dummy/app/templates/index.hbs

If merged, this PR makes some updates to the header and hero area based on design review.
- removed underline from HC logo on hover
- added underline to grid links on hover
- removed h3's
- spaced out the navbar more to balance it out a bit more
- aligned the grid paragraph text to be under the text only (not the icon)
Examples: 

header and hero updates per design review

---

ember-flight-icons/tests/acceptance/index-test.js
ember-flight-icons/tests/dummy/app/templates/index.hbs

The goal of this PR is to give a simple test to confirm that the docs are rendering at least one icon in the list of icons. This will help guard against any unintended breakage as we refactor how we are ingesting the catalog.json file.

add simple acceptance test to confirm docs are rendering icons

---

ember-flight-icons/tests/dummy/app/components/ds-toggle-button.hbs
ember-flight-icons/tests/dummy/app/components/ds-toggle-button.js
ember-flight-icons/tests/dummy/app/controllers/application.js
ember-flight-icons/tests/dummy/app/routes/index.js
ember-flight-icons/tests/dummy/app/styles/app.css
ember-flight-icons/tests/dummy/app/templates/index.hbs

If merged, this PR resolves #169 by adding the toggle button for the icon size.
So far: 
Examples: 

enhancement: add toggle button

---

ember-flight-icons/tests/dummy/app/templates/engineering.hbs

If merged, this PR formats the engineering docs with the same layout classes as the design docs page.
Examples: 

updated eng docs to use same layout classes as design docs

---

ember-flight-icons/tests/dummy/app/components/ds-footer.hbs
ember-flight-icons/tests/dummy/app/styles/app.css
ember-flight-icons/tests/dummy/app/styles/footer.css

If merged, this PR adds a footer to the documentation site
Examples: 

enhancement: added footer info to docs site

---

.github/workflows/ci-ember-flight-icons.yml
ember-flight-icons/package.json
ember-flight-icons/tests/acceptance/index-test.js
ember-flight-icons/yarn.lock

Adds a Percy snapshot to the icon viewer page at https://flight-hashicorp.vercel.app/ so that we can more easily test exports from the script etc. I added the PERCY_TOKEN to the GitHub repo and set up Percy to only test in Chrome for now. 
Follow-on to https://github.com/hashicorp/flight/pull/209#discussion_r708645146
Ref:
- https://docs.percy.io/docs/ember
- https://docs.percy.io/docs/github-actions
- hashicorp/waypoint#1813
- https://github.com/percy/example-percy-ember/blob/master/.github/workflows/test.yml
//
Resolves: https://github.com/hashicorp/flight/issues/93
Note: We can close this if we don't want to integrate, just seems like a nice gut check. 
// 
To check out Percy, click Percy "Details" below:
You may need to be added to the account and I will xpost on Slack now.

Add Percy to test visual diffs to icon viewer page

---

flight-icons/LICENSE.md

If merged, this PR will add a `LICENSE.md` file (Mozilla Public License Version 2.0) to the `flight-icons` folder, similar to the one we have in the `ember-flight-icons` folder (Lerna was complaining about it).

Add LICENSE.md file to “flight-icons” folder

---

ember-flight-icons/tests/acceptance/index-test.js

Add back test, with more specificity 
It's possible that in CI, the test was waiting for the icons at the top linking to the docs in the rectangular grid, not the full set of icons below, as can't repro locally.
Note: Update this PR if https://github.com/hashicorp/flight/pull/219 lands, maybe with the first data-test-icon name in .ds-icon-frame
Resolves: https://github.com/hashicorp/flight/issues/207

Add back test, with more specificity

---

ember-flight-icons/CONTRIBUTING.md
flight-icons/CONTRIBUTING.md

This is a slight update to the docs as-is. 
//
I'm still looking at release-it (https://github.com/hashicorp/flight/issues/115), is my first time using it. 
I see some benefit to automating it... but we have to keep in mind that one package could be bumped differently than the other. There are instances where we will only bump `@hashicorp/ember-flight-icons` and not `@hashicorp/flight-icons`. So... I would suggest we keep the releases atomic, which I think relates to the overarching goal of Cristiano's vision (flight-icons-svg could be consumed by ember-flight-icons, a potential future react-flight-icons etc.)
The idea behind the ticket is to get release-it to release both ember-flight-icons  package.json and flight-icons package.json within the "monorepo" we have right now, perhaps with …

Update npm docs

---

ember-flight-icons/addon/components/flight-icon.hbs
ember-flight-icons/package.json
ember-flight-icons/tests/dummy/app/templates/engineering.hbs
ember-flight-icons/yarn.lock

If merged, this PR resolves the issue where the `data-test-icon` attribute had no value. It now explicitly sets the value to `{{@name}}`.
The docs have also been updated to reflect this change. 
The `ember-test-selectors` ([an Ember testing addon](https://github.com/simplabs/ember-test-selectors)) has been added to help ensure that `data-test-*` attributes are stripped properly from production builds. 
Resolves #31 
Examples: 

Bugfix: resolves issue where the data-test-icon attribute had no value

---

ember-flight-icons/package.json
ember-flight-icons/yarn.lock
flight-icons/.npmignore
flight-icons/package.json
flight-icons/yarn.lock

This is the second part of the PR to solve #188. 
The **important** :) one.
In this PR I have added entries in the `package.json` files of `flight-icons` and `ember-flight-icons`, to run scripts that bump the version in the `package.json` file (interactively) and the publish the package to the NPM repository.
We have decided to use this simple package ([version-bump-prompt](https://github.com/JS-DevTools/version-bump-prompt)) to do interactive bumping (the user can easily select which semver bump they want to do), which is very similar to what [release-it](https://github.com/release-it/release-it) does from what I understood from @amyrlam and @MelSumner.
This should now allow us to release packages in production, from now on.

Export script (Node version) - Releasing (PR - Part #2: Node script to publish)

---

ember-flight-icons/package.json
flight-icons/package.json

I have split the “bump” command from the actual “npm publish” action. In this way they can be run independently, and we can have a specific PR on the update of the version (per conversation in: https://github.com/hashicorp/flight/pull/229#discussion_r710986676)

Split the “bump” command from the actual “publish” action

---

ember-flight-icons/tests/acceptance/index-test.js
ember-flight-icons/tests/dummy/app/router.js
ember-flight-icons/tests/dummy/app/routes/percy-test.js
ember-flight-icons/tests/dummy/app/templates/percy-test.hbs

Additional test to test icons in isolation. Route is hidden, have to manually navigate to /percy-test in the browser. If we added or removed an icon, the index Percy test diff would not be helpful at all.
Resolves: https://github.com/hashicorp/flight/issues/231

Add percy-test route with snapshot test

---

ember-flight-icons/CONTRIBUTING.md
ember-flight-icons/tests/dummy/app/templates/engineering.hbs
flight-icons/CONTRIBUTING.md

This is the last part of the PR to solve #188. 
In this PR I have:
- updated the CONTRIBUTE documentation for both the `flight-icons` and `ember-flight-icons`, reorganizing some content and adding specific instructions to follow for the "release" of npm packages.
- made a small change to a path in the documentation for developers in the mini-website

Export script (Node version) - Releasing (PR - Part #3: Documentation)

---

ember-flight-icons/tests/dummy/app/styles/components/ds-icon-grid.css

If merged, this PR resolves issue where a Safari bug was preventing correct use of the live-filter on the icons. 
Resolves #228 
Examples: 

Bugfix: resolves Safari issue

---

ember-flight-icons/CONTRIBUTING.md
flight-icons/CONTRIBUTING.md

Resolves: part of https://github.com/hashicorp/flight/issues/240
One more tweak to the instructions, seems like following this PR, @MelSumner can give https://github.com/hashicorp/flight/issues/240 a try at any point that's convenient this week.

Add manual real-world QA instructions

---

ember-flight-icons/package.json
ember-flight-icons/public/icons/catalog.json
flight-icons/package.json

If merged, this PR bumps `flight-icons` to v0.0.9-rc and `ember-flight-icons` to v0.0.3-rc.

yarn bump for rc

---

ember-flight-icons/package.json
flight-icons/package.json

If merged, this PR will add `git tag` to the `release` step (as requested by @Dhaulagiri).
Notice: this is the format I am using, but open to suggestions if you have a better idea:
https://github.com/hashicorp/flight/tags

Add automatic git tagging to "release" step

---

ember-flight-icons/ember-cli-build.js

file is no longer part of this addon
With https://github.com/hashicorp/flight/pull/271 this is no longer necessary
Verify things are working in vercel
Examples: 

don't finger print sprite file

---

README.md
RELEASE.md
ember-flight-icons/CONTRIBUTING.md
flight-icons/CONTRIBUTING.md

In this PR I have **reorganised** and **updated** (following the recent updates to the sync/build/release flow, and format of the SVG artefacts) the content of the `CONTRIBUTING.md` files for both `flight-icons` and `ember-flight-icons`, creating a new, single `RELEASE.md` file at the root of the project, with details on how to do a release of the packages (and the website).
This closes #265.
Examples: 

Update and reorganise the content for the “CONTRIBUTING” and “RELEASE” markdown files

---

ember-flight-icons/package.json
flight-icons/package.json

If merged, this PR bumps the version of `flight-icons` and `ember-flight-icons` to v1.0.0

bump for 1.0 release

---

ember-flight-icons/package.json
ember-flight-icons/yarn.lock

If merged, this PR updates the `flight-icons` dependency in `ember-flight-icons` for the 1.0.0 release.

updated flight-icons dep in prep for 1.0 release

---

ember-flight-icons/tests/dummy/app/styles/app.css
ember-flight-icons/tests/dummy/app/templates/engineering.hbs

Clean up .css file for readability
Rename `kbd` to `code`, to follow semantic HTML …
- Ref: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/kbd
Fix missing space
Also:
- Lint
- Add missing `code` callouts
***
revamp of https://github.com/hashicorp/flight/pull/251/files. i realize it seems minor, and that `ember-prism` brings in a LOT of global styles, but i think it's important that we trend toward semantic HTML
if you review commit-by-commit, may be easier to follow. pls lmk what you think

Use more semantic html in /engineering

---

ember-flight-icons/package.json
ember-flight-icons/yarn.lock

bumping flight-icons package so that new icons like `facebook` are visible on the website. normally this would trigger a percy change, i can work on that ticket today
builds off of https://github.com/hashicorp/flight/pull/288 and https://github.com/hashicorp/flight/pull/289

Bump flight-icons in ember-flight-icons to add icons to viewer

---

ember-flight-icons/addon/components/flight-icon.hbs
ember-flight-icons/addon/components/flight-icon.js
ember-flight-icons/tests/dummy/app/templates/engineering.hbs
ember-flight-icons/tests/dummy/app/templates/percy-test.hbs
ember-flight-icons/tests/integration/components/flight-icon-test.js

If merged, this PR will fix #327.
I have:
- added support for the “stretched” prop in the “FlightIcon” Ember addon
- updated the “percy-test” page
- updated the "engineering" documentation
- updated the unit tests
At the beginning I thought to use the `size` parameter, with a `stretch` value, but then I realized we use it to extrapolate the asset name, so it would not work (how do we know in that case which one of the two assets in two different sizes to use?).
/cc @hashicorp/design-systems

ember flight icon liquid size

---

ember-flight-icons/package.json

If merged, this PR will bump the `ember-flight-icons` addon to version 1.2.0.
_Notice: if you think this should be a `major` version change, happy to update it to `2.0.0`_

Bump “ember-flight-icons” to 1.2.0

---

.github/ISSUE_TEMPLATE/icon-request.md

I have noticed that designers asking for new icons are not attaching screenshots to the issue or linking to the relevant Figma files.
These are useful information for our team's designers to have context of how the icons are used, possible use cases, etc. (also the screenshots are helpful in the future to understand which icon we were referring to).
We want to make this more evident, so I have added a couple of entries to the list, and removed the previous one (which probably was too generic and seemed optional).

Update issue template for new icons

---

ember-flight-icons/addon/components/flight-icon.js
ember-flight-icons/package.json
ember-flight-icons/tests/integration/components/flight-icon-test.js

I have fixed an error in the `svgSize` method, where the `height` value was returned only if the `stretched` parameter was `true` (and so the `height` attribute was not assigned to the SVG element).
I have also bumped the `ember-flight-icon` addon version to `1.2.1` so if approved can be released straightaway.

fix bug in flight-icon.js

---

ember-flight-icons/package.json
ember-flight-icons/yarn.lock

In this PR I have:
- bumped the `flight-icons` dependency for `ember-flight-icons` to use the latest version (2.0.0) - see #341 
- updated `ember-flight-icons` package version to 1.2.2

Bump ember-flight-icon

---

.github/pull_request_template.md

The template seems long. Leaving the template as is proposed in the PR here in the description. 
- Suggesting to remove things that seem heavy-handed for this repo
- Wasn't sure why "conventional comments" was a h3 also
***

Streamline template

---

ember-flight-icons/package.json
ember-flight-icons/yarn.lock

Bump package, adds `hcp` icon
Can add dependabot for just this package as a safeguard for us as a follow-on
Same ubuntu-latest error as https://github.com/hashicorp/flight/pull/354#issuecomment-999810812, can ignore for now
IS: +2 icons `hcp`
***

Bump package, adds "hcp" icon

---

.github/dependabot.yml

Ref: We noticed forgot to bump flight-icons in ember-flight-icons here: https://github.com/hashicorp/flight/pull/356
Note: Can't really test this until it's merged. 
cc @didoo @MelSumner 
***

Add dependabot for HashiCorp packages

---

website/app/templates/engineering.hbs

This resolves #388.
In this PR I have updated the documentation for engineers, to better specify how React devs can use Flight icons in their codebases.
Preview: https://flight-git-update-docs-for-devs-to-clarify-react-hashicorp.vercel.app/engineering#use-react
Please review:
- content (meaning)
- readability
- syntax errors 😀
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1201709612443847

Update engineering documentation to better specify how React devs can use Flight icons

---

website/app/templates/engineering.hbs

In [this Slack comment](https://hashicorp.slack.com/archives/C7KTUHNUS/p1643048914096100?thread_ts=1643048240.095000&cid=C7KTUHNUS) @ashleemboyer raises a couple of valid points:
- The description under the “React/SVG” heading is the same as the one under “Inline SVG”
- We’ve been importing the icons like this in dev-portal, which is different from what I’m seeing in this page. I tried copy/pasting what’s in the docs and I’m getting some errors. Will have to investigate a little further but need to join to a meeting in a few `import { IconArrowRight16 } from '@hashicorp/flight-icons/svg-react/arrow-right-16'`
In this PR I have fixed both issues.
Preview: https://flight-git-update-docs-for-react-devs-hashicorp.vercel.app/engineering#use-react

Update documentation for React developers after feedback

---

ember-flight-icons/package.json

In this PR I have:
- bumped the version of “ember-flight-icon” to `2.0.1` (the addon CSS was changed)

bumped “ember-flight-icon” to 2.0.1

---

website/package.json
website/yarn.lock

In this PR I have bumped the `ember-flight-icon` dependency to `2.0.1`

bump website dependency
