hashicorp/flight

ember-flight-icons/README.md

Add badge for icons CI

---

ember-flight-icons/package.json

Extracted from: https://github.com/hashicorp/flight/pull/70
Made this tweak based on me publishing @hashicorp/flight-icons in https://github.com/hashicorp/flight/pull/69.

Update the package.json

---

.gitignore
pull_request_template.md

If merged, this PR adds a pull request template per [GitHub's instructions](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates) and some sensible defaults. 
Please consider using [conventional comments](https://conventionalcomments.org/) when reviewing this PR.

Internal: Add pull request template

---

.github/pull_request_template.md

i think we want the examples to appear so visible to the reviewer, what do you think

Tweak to the PR template

---

README.md

Added a link to the Flight mini-website in the README file (always handy to have it there).
Examples: 

Add link to the micro-website in the README file

---

.github/workflows/ci-ember-flight-icons.yml

Pros: makes the tests run no matter where changes triggered in the codebase and we can then require them to pass
Cons: Runs tests for code even if none of that code has changed

internal: run ci on all changes

---

README.md

Organize packages into table

---

ember-flight-icons/ember-cli-build.js
ember-flight-icons/package.json
ember-flight-icons/tests/dummy/app/styles/app.css
ember-flight-icons/tests/dummy/app/styles/tailwind.config.js
ember-flight-icons/yarn.lock

This PR lays the foundation for using tailwind for our docs. It currently does not actually import the tailwind styles at all since they break our existing design, but you can enable them for local testing and/or in subsequent PRs when we actually implement the new design.
Pull down the PR and add a tailwind class to a template and confirm it shows up correctly
```
error tailwindcss@2.2.11: The engine "node" is incompatible with this module. Expected version ">=12.13.0". Got "10.24.1"
```

Initial step to migrate docs to tailwind

---

ember-flight-icons/tests/dummy/app/styles/app.css

The previous list was incomplete and when uncommented would not have given us access to all the classes

add correct tailwind imports

---

ember-flight-icons/package.json
ember-flight-icons/tests/dummy/app/styles/app.css
ember-flight-icons/tests/dummy/app/styles/tailwind.config.js
ember-flight-icons/tests/dummy/app/styles/typography.css
ember-flight-icons/tests/dummy/app/templates/index.hbs
ember-flight-icons/yarn.lock

If merged, this PR updates the search and aligns spacing with the design.
- added form plugin for tailwind
- aligned on margins for some typographic elements
- updated the form input
Examples: 

enhancements to align with design

---

.github/workflows/ci-ember-flight-icons.yml
ember-flight-icons/config/ember-try.js

with github ci there is no real value to running tests that we allow to fail because you would have to manually inspect each one to figure out if the test passed or not. Since we are ok with them not passing we might as well not run them at all and save 3 run's worth of resources.

don't bother running tests we are allowing to fail

---

ember-flight-icons/ember-cli-build.js
ember-flight-icons/package.json
ember-flight-icons/tests/dummy/app/routes/application.js
ember-flight-icons/tests/dummy/app/styles/app.css
ember-flight-icons/tests/dummy/app/templates/engineering.hbs
ember-flight-icons/yarn.lock

If merged, this PR should fix some prettier/formatting issues and also adds code highlighting.
Examples: 

enhancement: add code highlighting

---

ember-flight-icons/ember-cli-build.js
ember-flight-icons/package.json
ember-flight-icons/tests/dummy/app/routes/application.js
ember-flight-icons/tests/dummy/app/styles/app.css
ember-flight-icons/tests/dummy/app/templates/engineering.hbs
ember-flight-icons/yarn.lock

If merged, this PR adds functionality to copy some of the code samples to the user's clipboard
- used [ember-prism](https://github.com/shipshapecode/ember-prism)
Examples: 

added copy to clipboard functionality for code samples

---

scripts/package.json
scripts/yarn.lock

Update figma-exporter dependencies in package.json

---

ember-flight-icons/package.json
flight-icons/package.json

I'm going to run a quick test in external app to make sure this package works - it works!
- Ran a `yarn release` in `flight-icons/` and `ember-flight-icons/`
- Note: We publish to npm before committing to GitHub
Testing:
- flight-icons: https://github.com/hashicorp/boundary-ui/pull/761 can see namespace change `flight-icons/svg`
- ember-flight-icons: https://github.com/hashicorp/design-system-playground/pull/5

Bump packages

---

ember-flight-icons/CONTRIBUTING.md
flight-icons/CONTRIBUTING.md

Feel free to suggest changes on GitHub (https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request) or commit directly to the branch if anything is wrong.
- I removed GitHub Actions since that seems N/A now. 
- 👉 Please review commit-by-commit, I committed some stylistic changes separately. (I'm interested in adding https://github.com/hashicorp/flight/issues/92 to the repo but I'd like to wait for consensus on https://github.com/hashicorp/flight/pull/233 first, as `markdownlint` can be a bit noisy. It does have some nice a11y benefits though! I'm biased cause I prefer to lint everything so that PR's are easier to review / stylistic choices are solved by tooling.)
Resolves: Part of #240, once this is …

Update docs for npm instructions

---

flight-icons/scripts/build-parts/generateBundleSVG.ts
flight-icons/scripts/build-parts/optimizeAssetsSVG.ts

Following up from the meeting, what do you think about this change? Not super important, just a suggestion
I added the console.log back, but wasn't sure if there was a reason it was commented out?

Tweak instructions

---

CONTRIBUTING.md
ember-flight-icons/tests/dummy/app/templates/index.hbs

If merged, this PR will:
- add a missing link in the micro-website documentation to the "root" CONTRIBUTING file in the repo
- add a small tweak to the linked file itself

Add missing link in the micro-website documentation

---

flight-icons/catalog.json

If merged, this PR regenerates assets in prep for a version bump

regen assets in prep for version bump

---

ember-flight-icons/CONTRIBUTING.md
ember-flight-icons/tests/dummy/app/templates/engineering.hbs

lmk if you have any feedback, replaces https://github.com/hashicorp/flight/pull/252

Copy and style edits to /engineering

---

.github/workflows/ci-ember-flight-icons.yml

Until we can figure out why the changes coming in for https://github.com/hashicorp/flight/pull/245 are causing Percy to not work we should stop running those checks

disable percy

---

ember-flight-icons/tests/dummy/app/templates/engineering.hbs

If merged, this PR will introduce a small update/fix to the documentation for developers in the micro-website.

Small update to the documentation for developers in the micro-website

---

CONTRIBUTING.md
README.md
ember-flight-icons/README.md
ember-flight-icons/tests/dummy/app/templates/engineering.hbs
flight-icons/README.md

cleans up some of the WIP language floating around the project

remove WIP language

---

ember-flight-icons/tests/dummy/app/templates/design.hbs
ember-flight-icons/tests/dummy/app/templates/index.hbs

Use Title Case for all headers
- Per: https://github.com/hashicorp/flight/blob/main/ember-flight-icons/CONTRIBUTING.md#copy-standards
Fix broken link and update order 
- We present ember-flight-icons first on /engineering, should be consistent

Updates to /design

---

flight-icons/package.json

release flight-icons 1.1.0

---

.github/ISSUE_TEMPLATE/icon-request.md

- added Heather/Hector as assignee for the new tickets
- added new label "Icon Request"

Update "Icon Request" issue template

---

README.md
ember-flight-icons/tests/dummy/app/templates/design.hbs
ember-flight-icons/tests/dummy/app/templates/engineering.hbs

Adds a brief note that there is a file containing mappings between structure icon names and flight icon names

add note on structure-icons mapping

---

ember-flight-icons/tests/dummy/app/components/ds-icon-grid.hbs
ember-flight-icons/tests/dummy/app/components/ds-icon-grid.js
ember-flight-icons/tests/dummy/app/styles/components/ds-icon-grid.css

Closes #350 
Closes #351
22 at 12 11 22" src="https://user-images.githubusercontent.com/1672302/147136900-62c7a654-f7d0-4d3c-9bce-7667645b3b9f.png">

update design to include keywords and ember/react names

---

ember-flight-icons/tests/dummy/app/components/ds-icon-grid.js

This was added in https://github.com/hashicorp/flight/pull/128 but as far as I can tell is not actually used anywhere

remove unused iconHbsCode function

---

ember-flight-icons/package.json
ember-flight-icons/tests/acceptance/index-test.js
ember-flight-icons/tests/dummy/app/components/ds-icon-grid.hbs
ember-flight-icons/tests/dummy/app/components/ds-icon-grid.js
ember-flight-icons/tests/dummy/app/controllers/index.js
ember-flight-icons/tests/dummy/app/routes/index.js
ember-flight-icons/tests/dummy/app/templates/index.hbs
ember-flight-icons/yarn.lock

Closes #238 
* Migrated search logic to a controller to allow for binding to query params more easily
* Used ember-concurrency to simplify debounce behavior 
* Added minimal state for when no results are returned
* It would probably be a good idea to add some tests for this?
There are most definitely room for improvements as my octane ember knowledge is pretty limited.
***

bind search queries to url for share-ability

---

website/app/components/ds-footer.hbs
website/app/components/ds-icon-grid.hbs
website/app/index.html
website/app/templates/application.hbs
website/app/templates/design.hbs
website/app/templates/engineering.hbs
website/app/templates/index.hbs

- Copy polish 
- Use characters in ember-prism code samples when possible
- Follow typography guidelines https://design-system-components-hashicorp.vercel.app/components/typography
Add language for a11y 
-This brings the Lighthouse score from 98 to 100 on the index page
- Fix links on index
In working on https://github.com/hashicorp/design-system-components/pull/122, I was going to debug ember-prism here since is open source. But, I ended up getting ember-prism to work in .hbs most of the time, except for `{` and `}` characters, which I can debug separately.
The best way to review this will be to have a look at the webpages as a whole on the Vercel. There were a lot of "on the way" changes as is editing copy, which is why I didn't make more atomic commits. (If you're having trouble with …

Copy and ember-prism polish 

---

.github/workflows/ci-ember-flight-icons.yml
ember-flight-icons/config/ember-try.js

These were disabled because they failed due to issues with code in the dummy app. #361 moved the docs out of the dummy app so these work again now
***

restore embroider tests

---

.github/ISSUE_TEMPLATE/icon-request.md

In this PR I have updated the default assignees for the icon request template (removed @dizzyup, added @cveigt).

Updated assignee in issue template

---

README.md

This project is being merged into our new design system monorepo, therefore this PR updates the Readme here to indicate this project is archived.
We can merge this once the final tasks for the migration are complete

Update readme to reflect new home for Flight
